# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

#  fileSystems."/" =
#    { device = "/dev/disk/by-uuid/430e7309-ef59-495f-9298-8ac2a72482a4";
#      fsType = "ext4";
#    };

#  fileSystems."/boot" =
#    { device = "/dev/disk/by-uuid/DB65-3FF9";
#      fsType = "vfat";
#      options = [ "fmask=0022" "dmask=0022" ];
#    };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/41ab70c8-063f-4f95-a7c1-0fc28d1ca4c1";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C3BB-56D3";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
